import { AppStyle } from "../style/styles.slint";

export component AppText inherits Text {
    color: AppStyle.colors.foreground;
    font-size: AppStyle.fonts.default-size;
    font-family: AppStyle.fonts.family;
}

export component AppButton inherits Rectangle {
    in property <string> text;
    callback clicked;

    background: AppStyle.colors.secondary;
    border-color: AppStyle.colors.border;
    border-width: 1px;
    border-radius: 4px;

    AppText {
        text: root.text;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    TouchArea {
        clicked => { root.clicked(); }
    }
}

export component FloatingButton inherits Rectangle {
    in property <string> icon-source;
    callback clicked;

    width: 48px;
    height: 48px;
    background: AppStyle.colors.accent;
    border-radius: 24px;

    drop-shadow-color: #00000080;
    drop-shadow-blur: 5px;

    Image {
        source: root.icon-source;
        width: 24px;
        height: 24px;
        x: 12px;
        y: 12px;
    }

    TouchArea {
        clicked => { root.clicked(); }
    }
}

export component AppTextInput inherits Rectangle {
    in property <string> placeholder;
    in-out property <string> text;
    callback edited <=> text-input.edited;

    background: AppStyle.colors.background;
    border-color: AppStyle.colors.border;
    border-width: 1px;
    border-radius: 4px;

    forward-focus: text-input;

    AppText {
        text: root.text == "" ? root.placeholder : "";
        color: root.text == "" ? AppStyle.colors.secondary : AppStyle.colors.foreground;
        x: AppStyle.spacing.medium;
        y: AppStyle.spacing.medium;
        width: parent.width - 2 * AppStyle.spacing.medium;
        height: parent.height - 2 * AppStyle.spacing.medium;
        vertical-alignment: center;
    }

    text-input := TextInput {
        x: AppStyle.spacing.medium;
        y: AppStyle.spacing.medium;
        width: parent.width - 2 * AppStyle.spacing.medium;
        height: parent.height - 2 * AppStyle.spacing.medium;
        color: AppStyle.colors.foreground;
        font-size: AppStyle.fonts.default-size;
    }
}
