export global WindowInfo {
    in property<length> window-width: 1024px;
    in property<length> window-height: 768px;
    in property<bool> is-portrait: false;
}

export component WindowInfoHelper inherits Rectangle {
    function check-is-portrait() {
        if (WindowInfo.is-portrait != (self.width < self.height)) {
            WindowInfo.is-portrait = (self.width < self.height);
        }
    }

    changed width => {
        WindowInfo.window-width = self.width;
        self.check-is-portrait();
    }

    changed height => {
        WindowInfo.window-height = self.height;
        self.check-is-portrait();
    }
}
